name: HelloWorld

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    # Step 3: Install Surge globally
    - name: Install Surge
      run: npm install --global surge

    # Step 4: Check the directory contents (for debugging)
    - name: List directory contents
      run: ls -R

    # Step 5: Run any build step if necessary (if you're building a static site)
    # For example, if you're using npm build or any other build tool, add it here
    # If you have a build command (like `npm run build`), include it:
    # - name: Build the project (optional)
    #   run: npm run build

    # Step 6: Deploy using Surge
    - name: Deploy using Surge
      run: surge ./helloworldnew --token ${{ secrets.SURGE_TOKEN }}
