name: HelloWorld
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: npm install

    # Step 4: Run a set of commands using the runner's shell
    - name: Installing surge
      run: npm install --global surge
    - name: deploying using surge
      run: surge ./helloworldnew.surge.sh --token ${{secrests.SURGE_TOKEN}}

    
